config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :offenses, only: [:index] do 
        collection do 
          post 'offenses_pdf'
        end
      end
    end
  end
  root 'offenses#index'
  resources :offenses, only: [:index]
  devise_for :admin
  resources :offense_imports, only: [:new, :create]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offense.rb
class Offense < ApplicationRecord

  def new_offense_hash
    offense_hash = {}
    name = {first: self.first_name, middle: self.middle_name, last: self.last_name}
    address = {number: self.address_number, street: self.street, zip: self.zip, county: self.county, state: self.state}
    arrest_agency_address = {number: self.arrest_agency_address_number, street: self.arrest_agency_street, zip: self.arrest_agency_zip}
    arrest_agency = {name: self.arrest_agency_name, address: arrest_agency_address, date: self.arrest_date}

    offense_hash[:name] = name
    offense_hash[:sex] = self.gender
    offense_hash[:race] = self.race
    offense_hash[:dob] = self.dob
    offense_hash[:address] = address
    offense_hash[:file_number] = self.file_number
    offense_hash[:offense_description] = self.offense_description
    offense_hash[:offense_date] = self.offense_date
    offense_hash[:disposition] = self.disposition
    offense_hash[:disposition_date] = self.disposition_date
    offense_hash[:county_disposition] = self.county_disposition
    offense_hash[:arrest_agency] = arrest_agency
    offense_hash
  end

end

app/models/offense_import.rb
class OffenseImport
  include ActiveModel::Model
  require 'roo'

  attr_accessor :original_filename, :filepathname

  def initialize(attributes={})
    # attributes.each { |name, value| send("#{name}=", value) }
    @original_filename = attributes[:original_filename]
    @filepathname = attributes[:filepathname]
  end

  def persisted?
    false
  end

  def open_spreadsheet
    case File.extname(original_filename)
    when ".csv" then Csv.new(filepathname, nil, :ignore)
    when ".xls" then Roo::Excel.new(filepathname)
    when ".xlsx" then Roo::Excelx.new(filepathname)
    when ".ods" then Roo::OpenOffice.new(filepathname)
    else raise "Unknown file type: #{original_filename}"
    end
  end

  def load_imported_offenses
    spreadsheet = open_spreadsheet
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).map do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      offense = Offense.find_by_id(row["id"]) || Offense.new
      offense.file_number = row['File Number']
      offense.first_name = row['First Name']
      offense.middle_name = row['Middle Name']
      offense.last_name = row['Last Name']
      offense.gender = row['Gender']
      offense.race = row['Race']
      offense.dob = row['Date of Birth']
      offense.address_number = row['Street Number']
      offense.street = row['Street Name']
      offense.zip = row['Zip']
      offense.county = row['County']
      offense.state = row['State']
      offense.offense_description = row['Offense Description']
      offense.offense_date = row['Offense Date']
      offense.disposition = row['Disposition']
      offense.disposition_date = row['Disposition Date']
      offense.county_disposition = row['County Disposition']
      offense.arrest_date = row['Arrest Date']
      offense.arrest_agency_name = row['Arrest Agency Name']
      offense.arrest_agency_department = row['Arrest Agency Department']
      offense.arrest_agency_address_number = row['Arrest Agency Street Number']
      offense.arrest_agency_street = row['Arrest Agency Street Name']
      offense.arrest_agency_zip = row['Arrest Agency Zip']
      offense
    end
  end

  def imported_offenses
    @imported_offenses ||= load_imported_offenses
  end

  def save
    Offense.delete_all
    if imported_offenses.map(&:valid?).all?
      imported_offenses.each(&:save!)
      true
    else
      imported_offenses.each_with_index do |offense, index|
        offense.errors.full_messages.each do |msg|
          errors.add :base, "Row #{index + 2}: #{msg}"
        end
      end
      false
    end
  end

end

app/controllers/api/v1/offenses_controller.rb
class Api::V1::OffensesController < ApplicationController
   include ActionController::MimeResponds
   skip_before_action :verify_authenticity_token  

  # before_action :check_wild_cards
  def index
    offenses = Offense.all
    check_wild_cards
    unless @query.empty?
      if @first_name.present? # this is big if
        if @last_name.present?
          if @middle_name.present?
            offenses = Offense.where("first_name LIKE ? AND last_name LIKE ? AND middle_name LIKE ?", @first_name, @last_name, @middle_name)
          else
            offenses = Offense.where("first_name LIKE ? AND last_name LIKE ?", @first_name, @last_name)
          end
        elsif @middle_name.present?
          offenses = Offense.where("first_name LIKE ? AND middle_name LIKE ?", @first_name, @middle_name)
        else
          offenses = Offense.where("first_name LIKE ?", @first_name)
        end
      elsif @middle_name.present? # this is big elsif
        if @last_name.present?
          offenses = Offense.where("middle_name LIKE ? AND last_name LIKE ?", @middle_name, @last_name)
        else
          offenses = Offense.where("middle_name LIKE ?", @middle_name)
        end
      elsif @last_name.present? # another big elsf
        offenses = Offense.where("last_name LIKE ?", @last_name) # another big elsif
      else #this is big else
        render json: { status: "error", code: 400, message: "Can't find offenses without first_name, middle_name, or last_name" }
        return
      end
    end

    # Mapping here
    offenses = offenses.map do |offense| 
      offense.new_offense_hash
    end
    
    render json: offenses, status: :ok
  end
  
  def offenses_pdf
    respond_to do | format| 
      format.html
      format.pdf do
    pdf = OffensePdf1.new(request.parameters)
    send_data pdf.render, filename: 'Offenses.pdf',
                              type: 'application/pdf',
                              disposition: 'inline'
      end                        
    end                      
  end

  private

    def check_wild_cards
      if params[:q].present?
        @query = JSON.parse(params[:q])
        @first_name = @query["first_name"].gsub("*","%") if @query["first_name"].present?
        @middle_name = @query["middle_name"].gsub("*","%") if @query["middle_name"].present?
        @last_name = @query["last_name"].gsub("*","%") if @query["last_name"].present?
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Response
  include ExceptionHandler
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  # provides the more graceful `included` method
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/offense_imports_controller.rb
class OffenseImportsController < ApplicationController
  def new
    @offense_import = OffenseImport.new
  end

  def create
    if params["offense_import"].present? && params["offense_import"]["file"].present?
      @offense_import = OffenseImport.new(original_filename: (params["offense_import"]["file"]).original_filename,
        filepathname: (params["offense_import"]["file"]).path)
      if @offense_import.save
        redirect_to root_url
        flash[:success] = "Offenses uploaded successfully"
      else
        render :new
      end
    else
      redirect_to root_url
      flash[:success] = "You need to choose a file first"
    end
  end

  private

    def offense_import_params
      params.require(:offense_import).permit(:file)
    end
end

app/controllers/offenses_controller.rb
class OffensesController < ApplicationController
  before_action :authenticate_admin!

  def index
  end
end

app/helpers/api/v1/offenses_helper.rb
module Api::V1::OffensesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offense_imports_helper.rb
module OffenseImportsHelper
end

app/helpers/offenses_helper.rb
module OffensesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpungementServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/offense_imports/new.html.erb
<div class="offenses">
  <h4 class='mt-4 text-center'>Import Offenses from Excel</h4>

  <div class='card bg-light col-7 rounded mb-2 shadow mx-auto border-info'>
    <div class='card-body'>
      Note: The application will read your spreadsheet and attempt to find the
      objects by their IDs. It updates the record if it finds one, else, it creates a new record if the ID does not exist.
    </div>
  </div><br>

  <h5 class='text-center'>Select File</h5>
  <div class='card bg-light col-7 rounded mb-2 shadow mx-auto border-info'>
    <div class='card-body'>
      <%= form_for @offense_import do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.file_field :file %>
        <%= f.submit "Import File", class: "btn btn-info" %>
      <% end %>
    </div>
  </div>

  <div class='text-center'>
      <%= link_to "Back", :back, class: 'btn btn-primary mt-2' %>
  </div>
</div>

app/views/offenses/index.html.erb
<div class="offenses">
  <h1>Welcome to Expungement App!</h1><br/>

    <%= image_tag("expungement.jpeg", width: "900", height: "400")%><br/>
    <div class="links">
    <%= link_to "Log out", destroy_admin_session_path, method: :delete %><br/>
    <%= link_to "Upload offenses", new_offense_import_path %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Note: The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>